{
  "formatVersion": "1.1",
  "component": {
    "url": "../../quickjs-kt/1.0.15-yonto.1/quickjs-kt-1.0.15-yonto.1.module",
    "group": "io.github.kangzj",
    "module": "quickjs-kt",
    "version": "1.0.15-yonto.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "quickjs-linuxArm64Main.klib",
          "url": "quickjs-kt-linuxarm64-1.0.15-yonto.1.klib",
          "size": 238773,
          "sha512": "bcf973ee4dcf10a5b5bcf9569488091abb09f6832d6bf14af0b30b598b95c46f67c75f1d5ad4783ced1a76d272fe07eb64acd831180f046ab0d76c24690ac087",
          "sha256": "229e7d167a73f9534d92ea9693858182e9104b92f8a7b6c30fd02dfafaab1aa4",
          "sha1": "32cad0d16f20e1996ca5daf663722d4ebf1e4e7e",
          "md5": "2f2f5f6726213bea35b3b3e2c31ce1b8"
        },
        {
          "name": "quickjs-linuxArm64Cinterop-quickjsMain.klib",
          "url": "quickjs-kt-linuxarm64-1.0.15-yonto.1-cinterop-quickjs.klib",
          "size": 432867,
          "sha512": "3e924fcd3f2596b94517e32a06428e8101cde1cd6f362acce2ec6e61e74023d1cc84d08092e72b00d0c62018b88c9403d2f0487176a349f59a451eb855fccc7d",
          "sha256": "3e459cfd4a6ad037ad779abca39152c87692b799456325d0832fae29fe6c0d71",
          "sha1": "112ec7204536b200be93c03d6ea9f5838ef956f7",
          "md5": "a8a907bc90b794b03aa7353809392655"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "quickjs-linuxarm64-sources.jar",
          "url": "quickjs-kt-linuxarm64-1.0.15-yonto.1-sources.jar",
          "size": 49417,
          "sha512": "f5072965e11b3ef1dc8bd4892ec28df6e17e907d48bae5cc2c457d3b9d62afe5ac7e188f2aa795b1e69239fef49d30038d8826f441f13124f79a2e46a32bc841",
          "sha256": "d930e49956ed0577ce59a94b715b82df5255bc53edf340102706c409ed60b36f",
          "sha1": "1f157f103f14b8a43c1138f96b86d46c2978d25c",
          "md5": "cae20f77e4f5a6e3f61fdf9969c2b2b7"
        }
      ]
    }
  ]
}
