{
  "formatVersion": "1.1",
  "component": {
    "url": "../../quickjs-kt/1.0.15-yonto.1/quickjs-kt-1.0.15-yonto.1.module",
    "group": "io.github.kangzj",
    "module": "quickjs-kt",
    "version": "1.0.15-yonto.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "quickjs-macosArm64Main.klib",
          "url": "quickjs-kt-macosarm64-1.0.15-yonto.1.klib",
          "size": 238771,
          "sha512": "802e5fdda7b500927559650ddb2003692c5add040b2e37467042f906d67d575c7b34b28e897a86bcc7eda186dc68e1d8efe321cb389d58693708e23dbfe7b51d",
          "sha256": "77762fe7f99bb874275f33f746673e4432d55eaa9a2792607886029be8a218db",
          "sha1": "be609c02c8ab63383937e8b7539ef9ef97ce3fb7",
          "md5": "817be15f4bf503e882fc7f2ecabb90ce"
        },
        {
          "name": "quickjs-macosArm64Cinterop-quickjsMain.klib",
          "url": "quickjs-kt-macosarm64-1.0.15-yonto.1-cinterop-quickjs.klib",
          "size": 449285,
          "sha512": "7b5a263b3497e53d8fd2f2b89a8c025978459f3e1b4275f3eff8563d473f9541a5565f26998f3aebeeacdc6d9b998cfc70848ba6797b35e6cb43cd812516e8ff",
          "sha256": "bf00883afc79814f9ab050d12de86a2e8a5d91f98d749a5861511ea37d330f96",
          "sha1": "9f9a44a5429fcd9e53b77c6c041fe8b91f89465a",
          "md5": "a5cbba50f87d818a7b737ff3fb08b3fe"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "quickjs-macosarm64-sources.jar",
          "url": "quickjs-kt-macosarm64-1.0.15-yonto.1-sources.jar",
          "size": 49417,
          "sha512": "f5072965e11b3ef1dc8bd4892ec28df6e17e907d48bae5cc2c457d3b9d62afe5ac7e188f2aa795b1e69239fef49d30038d8826f441f13124f79a2e46a32bc841",
          "sha256": "d930e49956ed0577ce59a94b715b82df5255bc53edf340102706c409ed60b36f",
          "sha1": "1f157f103f14b8a43c1138f96b86d46c2978d25c",
          "md5": "cae20f77e4f5a6e3f61fdf9969c2b2b7"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "quickjs-macosarm64-metadata.jar",
          "url": "quickjs-kt-macosarm64-1.0.15-yonto.1-metadata.jar",
          "size": 50164,
          "sha512": "541260c6619e33ea825909a63df44420b2668d7f7d67aa85fcfe870d51a9ca892c00bab1781d6f1e80c3d8274c426093dc90da816bc877ca4f868dc0bfea632c",
          "sha256": "b4085d88872917be80e3fabb177dd40d531aecbcf2adfb6545ea74fe6d987fb2",
          "sha1": "640c2038f4c2dd699355e007530cb6eda1d9c0fe",
          "md5": "328f71e4659d3cc46592e90980aa822d"
        }
      ]
    }
  ]
}
