{
  "formatVersion": "1.1",
  "component": {
    "url": "../../quickjs-kt/1.0.15-yonto.1/quickjs-kt-1.0.15-yonto.1.module",
    "group": "io.github.kangzj",
    "module": "quickjs-kt",
    "version": "1.0.15-yonto.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "quickjs-iosX64Main.klib",
          "url": "quickjs-kt-iosx64-1.0.15-yonto.1.klib",
          "size": 238745,
          "sha512": "c817ade541da39b978eeac474023b1b86254fda071214ac9b4d9f8d4977ee7594467a35f1552d8febcbaa47eb8615b1b7e1bb600c43bd316364abe7a7314f89b",
          "sha256": "9520b4d9381d1f3680405528742e9be272e9ec0fce067190461e1d359bbae02a",
          "sha1": "38139abd603bceb6a8468e507a2a86370e1d9265",
          "md5": "7dfaa8337060a0ca6af083d49119c77a"
        },
        {
          "name": "quickjs-iosX64Cinterop-quickjsMain.klib",
          "url": "quickjs-kt-iosx64-1.0.15-yonto.1-cinterop-quickjs.klib",
          "size": 434528,
          "sha512": "68990a181404c8a9d43481b56dd553f449bf74a33c25bcaf5e26b36e0f1bbf2e67f5076d058f7056f540f60acca6ea53ede9f8e7999eecf182a301802acca852",
          "sha256": "cd70d19b30068b41fc438aaebffddf2aa3ad093fd058fa4efe212b9ab26d2dd5",
          "sha1": "95997a3119a72bc561ef95c68dbfd06723fa82ab",
          "md5": "1815eeb6d2225af7cf4287e019aa24a8"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "quickjs-iosx64-sources.jar",
          "url": "quickjs-kt-iosx64-1.0.15-yonto.1-sources.jar",
          "size": 49417,
          "sha512": "f5072965e11b3ef1dc8bd4892ec28df6e17e907d48bae5cc2c457d3b9d62afe5ac7e188f2aa795b1e69239fef49d30038d8826f441f13124f79a2e46a32bc841",
          "sha256": "d930e49956ed0577ce59a94b715b82df5255bc53edf340102706c409ed60b36f",
          "sha1": "1f157f103f14b8a43c1138f96b86d46c2978d25c",
          "md5": "cae20f77e4f5a6e3f61fdf9969c2b2b7"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "quickjs-iosx64-metadata.jar",
          "url": "quickjs-kt-iosx64-1.0.15-yonto.1-metadata.jar",
          "size": 50164,
          "sha512": "541260c6619e33ea825909a63df44420b2668d7f7d67aa85fcfe870d51a9ca892c00bab1781d6f1e80c3d8274c426093dc90da816bc877ca4f868dc0bfea632c",
          "sha256": "b4085d88872917be80e3fabb177dd40d531aecbcf2adfb6545ea74fe6d987fb2",
          "sha1": "640c2038f4c2dd699355e007530cb6eda1d9c0fe",
          "md5": "328f71e4659d3cc46592e90980aa822d"
        }
      ]
    }
  ]
}
