{
  "formatVersion": "1.1",
  "component": {
    "url": "../../quickjs-kt/1.0.15-yonto.1/quickjs-kt-1.0.15-yonto.1.module",
    "group": "io.github.kangzj",
    "module": "quickjs-kt",
    "version": "1.0.15-yonto.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "quickjs-jvm.jar",
          "url": "quickjs-kt-jvm-1.0.15-yonto.1.jar",
          "size": 2314277,
          "sha512": "7995e4f7063309f6730b4f82c9217753ed9d551b36975a3b8c6d9a99acf0d28417e6a25ad556f858f6e27c69cb387c126c19c91d9dbc44fe2d54a60210b1ffa5",
          "sha256": "ba7b7bcd7507010d115f0046361ab9f1d80b7bd09b8323b69ccd67714402a5e0",
          "sha1": "a775dd60425bdbaad5c6f9e35d500cecd988f3f2",
          "md5": "66ab3e1e01512ce6b85103d9afe70fe6"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "quickjs-jvm.jar",
          "url": "quickjs-kt-jvm-1.0.15-yonto.1.jar",
          "size": 2314277,
          "sha512": "7995e4f7063309f6730b4f82c9217753ed9d551b36975a3b8c6d9a99acf0d28417e6a25ad556f858f6e27c69cb387c126c19c91d9dbc44fe2d54a60210b1ffa5",
          "sha256": "ba7b7bcd7507010d115f0046361ab9f1d80b7bd09b8323b69ccd67714402a5e0",
          "sha1": "a775dd60425bdbaad5c6f9e35d500cecd988f3f2",
          "md5": "66ab3e1e01512ce6b85103d9afe70fe6"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "quickjs-jvm-sources.jar",
          "url": "quickjs-kt-jvm-1.0.15-yonto.1-sources.jar",
          "size": 35715,
          "sha512": "4b83603558c183fa966c13a58cb08e45dd1a9c2b25a6f967fb269804da297796f0b6f721b76a197826ebe315108fa8438f7ba9d19519ceb38ab027cca130ffec",
          "sha256": "df8f743f2409d195b64bdf0fa169476ed399a2832663dcbdd8ffd59b3c774763",
          "sha1": "c603cc81aa010b12032f8700d3e84e9bcfe8f31d",
          "md5": "4a6e4f6051165ad9876114220e4488e2"
        }
      ]
    }
  ]
}
